
package org.projet.libraryservice.webapp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ListeLivres", targetNamespace = "http://webapp.libraryservice.projet.org/", wsdlLocation = "http://linux.home:8080/libraryservice-webapp2535157108091288188/ListeLivres?wsdl")
public class ListeLivres_Service
    extends Service
{

    private final static URL LISTELIVRES_WSDL_LOCATION;
    private final static WebServiceException LISTELIVRES_EXCEPTION;
    private final static QName LISTELIVRES_QNAME = new QName("http://webapp.libraryservice.projet.org/", "ListeLivres");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://linux.home:8080/libraryservice-webapp2535157108091288188/ListeLivres?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LISTELIVRES_WSDL_LOCATION = url;
        LISTELIVRES_EXCEPTION = e;
    }

    public ListeLivres_Service() {
        super(__getWsdlLocation(), LISTELIVRES_QNAME);
    }

    public ListeLivres_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), LISTELIVRES_QNAME, features);
    }

    public ListeLivres_Service(URL wsdlLocation) {
        super(wsdlLocation, LISTELIVRES_QNAME);
    }

    public ListeLivres_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LISTELIVRES_QNAME, features);
    }

    public ListeLivres_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ListeLivres_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ListeLivres
     */
    @WebEndpoint(name = "ListeLivresPort")
    public ListeLivres getListeLivresPort() {
        return super.getPort(new QName("http://webapp.libraryservice.projet.org/", "ListeLivresPort"), ListeLivres.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ListeLivres
     */
    @WebEndpoint(name = "ListeLivresPort")
    public ListeLivres getListeLivresPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webapp.libraryservice.projet.org/", "ListeLivresPort"), ListeLivres.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LISTELIVRES_EXCEPTION!= null) {
            throw LISTELIVRES_EXCEPTION;
        }
        return LISTELIVRES_WSDL_LOCATION;
    }

}
