
package org.projet.libraryservice.webapp;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ListeLivres", targetNamespace = "http://webapp.libraryservice.projet.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ListeLivres {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLivreid", targetNamespace = "http://webapp.libraryservice.projet.org/", className = "org.projet.libraryservice.webapp.GetLivreid")
    @ResponseWrapper(localName = "getLivreidResponse", targetNamespace = "http://webapp.libraryservice.projet.org/", className = "org.projet.libraryservice.webapp.GetLivreidResponse")
    @Action(input = "http://webapp.libraryservice.projet.org/ListeLivres/getLivreidRequest", output = "http://webapp.libraryservice.projet.org/ListeLivres/getLivreidResponse")
    public String getLivreid();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setLivreid", targetNamespace = "http://webapp.libraryservice.projet.org/", className = "org.projet.libraryservice.webapp.SetLivreid")
    @ResponseWrapper(localName = "setLivreidResponse", targetNamespace = "http://webapp.libraryservice.projet.org/", className = "org.projet.libraryservice.webapp.SetLivreidResponse")
    @Action(input = "http://webapp.libraryservice.projet.org/ListeLivres/setLivreidRequest", output = "http://webapp.libraryservice.projet.org/ListeLivres/setLivreidResponse")
    public void setLivreid(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<org.projet.libraryservice.webapp.Livre>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListLivre", targetNamespace = "http://webapp.libraryservice.projet.org/", className = "org.projet.libraryservice.webapp.GetListLivre")
    @ResponseWrapper(localName = "getListLivreResponse", targetNamespace = "http://webapp.libraryservice.projet.org/", className = "org.projet.libraryservice.webapp.GetListLivreResponse")
    @Action(input = "http://webapp.libraryservice.projet.org/ListeLivres/getListLivreRequest", output = "http://webapp.libraryservice.projet.org/ListeLivres/getListLivreResponse")
    public List<Livre> getListLivre();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setListLivre", targetNamespace = "http://webapp.libraryservice.projet.org/", className = "org.projet.libraryservice.webapp.SetListLivre")
    @ResponseWrapper(localName = "setListLivreResponse", targetNamespace = "http://webapp.libraryservice.projet.org/", className = "org.projet.libraryservice.webapp.SetListLivreResponse")
    @Action(input = "http://webapp.libraryservice.projet.org/ListeLivres/setListLivreRequest", output = "http://webapp.libraryservice.projet.org/ListeLivres/setListLivreResponse")
    public void setListLivre(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Livre> arg0);

    /**
     * 
     * @return
     *     returns java.util.List<org.projet.libraryservice.webapp.Livre>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doListLivre", targetNamespace = "http://webapp.libraryservice.projet.org/", className = "org.projet.libraryservice.webapp.DoListLivre")
    @ResponseWrapper(localName = "doListLivreResponse", targetNamespace = "http://webapp.libraryservice.projet.org/", className = "org.projet.libraryservice.webapp.DoListLivreResponse")
    @Action(input = "http://webapp.libraryservice.projet.org/ListeLivres/doListLivreRequest", output = "http://webapp.libraryservice.projet.org/ListeLivres/doListLivreResponse")
    public List<Livre> doListLivre();

}
